name: Branch push test build

on:
  push:
    branches:
    # Match any new tag
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: true
      matrix:
        build:
          - name: it-tools-gui-win-amd64.exe
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: it-tools-gui
            platform: 'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
    
      - name: Build frontend assets
        shell: bash
        run: |
            npm install -g pnpm

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.23'
          wails-version: 'v2.9.3'

      - name: Checkout create-image
        uses: actions/checkout@v2
        with:
          repository: create-dmg/create-dmg
          path: ./build/create-dmg
          ref: master

      - name: Package Macos
        id: Package_Macos
        if: runner.os == 'macOS'
        working-directory: ./build
        run: |
          ./create-dmg/create-dmg \
            --no-internet-enable \
            --volname "it-tools-gui" \
            --volicon "bin/it-tools-gui.app/Contents/Resources/iconfile.icns" \
            --text-size 12 \
            --window-pos 400 400 \
            --window-size 660 450 \
            --icon-size 80 \
            --icon "it-tools-gui.app" 180 180 \
            --hide-extension "it-tools-gui.app" \
            --app-drop-link 480 180 \
            "bin/it-tools-gui-Mac-universal-$(date +%Y-%m-%d-%H-%M).dmg" \
            "bin"
          rm -rvf bin/it-tools-gui.app
      
      - uses: actions/upload-artifact@v4
        with:
          name: Wails Build ${{runner.os}}
          path: |
            */bin/
            *\bin\*

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*